### ISSUE TITLE
How many epochs did the pre-trained model have? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [calclavia/DeepJ#48]
I kept my machine up for 6 hours and trained for about 40 epochs.

**Comment by calclavia** [comment]
Around 2 days on NVIDIA Tesla 4K.

**Comment by DefinitlyEvil** [comment]
@calclavia omg that's a lot :O Now I figured why my network sucks. xD

**Comment by DefinitlyEvil** [comment]
Oh btw will this be possible to make it support multi-GPU training? That would be greatly increase the training speed since I got double Maxwell Titan X GPUs. :D

**Comment by calclavia** [comment]
@DefinitlyEvil Yes, but it's not on the top of our lists. If you want to make a PR, feel free to do so!

**Comment by DefinitlyEvil** [comment]
Alright. :( I am bad at complex models since I am a beginner.
