### ISSUE TITLE
site is forcing https while the api call is to http, causing error and no sound

### ISSUE THREAD

**Issue by gilamran** [calclavia/DeepJ#70]
on the console:
`GET http://18.222.90.74/stream.mp3?length=1000&seed=0&Baroque=0.0982352937586819&Classical=0.7525334207246455&Romantic=0.8340969462751091&Modern=0.8574476342870909 net::ERR_CONNECTION_REFUSED`

**Comment by taylorshin12** [comment]
This has been resolved.
