### ISSUE TITLE
how is train data fold like 

### ISSUE THREAD

**Issue by JucyCherry** [calclavia/DeepJ#72]
the folder data/ only contains midi?
I encountered error when i train model with data folder only contains midi.
So i wonder if there is some misunderstanding about the train data I built.
I'd appreciated if U can help me with the problem.（ฅ´ω`ฅ）

**Comment by calclavia** [comment]
The data folder is supposed to contain folders that contain various genres of music. This is how the model labels each genre of music.

**Comment by JucyCherry** [comment]
thank u !! 
but i still have some questions about the structure of the training data folder.
should i construct the trainning data folder  by classifying the midis to these three genres?
genre = [
    'baroque',
    'classical',
    'romantic'
]
**and the constant 'styles' in 'constant.py' mains smaller classifications than genre ?**
 styles = [
    [
        'data/baroque/bach',
        'data/baroque/handel',
        'data/baroque/pachelbel'
    ],
    [
        'data/classical/burgmueller',
        'data/classical/clementi',
        'data/classical/haydn',
        'data/classical/beethoven',
        'data/classical/brahms',
        'data/classical/mozart'
    ],
    [
        'data/romantic/balakirew',
        'data/romantic/borodin',
        'data/romantic/brahms',
        'data/romantic/chopin',
        'data/romantic/debussy',
        'data/romantic/liszt',
        'data/romantic/mendelssohn',
        'data/romantic/moszkowski',
        'data/romantic/mussorgsky',
        'data/romantic/rachmaninov',
        'data/romantic/schubert',
        'data/romantic/schumann',
        'data/romantic/tchaikovsky',
        'data/romantic/tschai'
    ]
]
**shoud i construct the fold like  'data/baroque/xxx.midi',or  'data/baroque/bach/xxx.midi'?**
the bigger classification or the smaller ?

**Comment by JucyCherry** [comment]
after i construct the training data fold like the styles and genres  in 'constant.py', the error dispeared

  styles = [
[
'data/baroque/bach',
'data/baroque/handel',
'data/baroque/pachelbel'
],
[
'data/classical/burgmueller',
'data/classical/clementi',
'data/classical/haydn',
'data/classical/beethoven',
'data/classical/brahms',
'data/classical/mozart'
],
[
'data/romantic/balakirew',
'data/romantic/borodin',
'data/romantic/brahms',
'data/romantic/chopin',
'data/romantic/debussy',
'data/romantic/liszt',
'data/romantic/mendelssohn',
'data/romantic/moszkowski',
'data/romantic/mussorgsky',
'data/romantic/rachmaninov',
'data/romantic/schubert',
'data/romantic/schumann',
'data/romantic/tchaikovsky',
'data/romantic/tschai'
]
