### ISSUE TITLE
Why the speed of training process so slow?

### ISSUE THREAD

**Issue by JucyCherry** [calclavia/DeepJ#74]
each my style folder only contrains 10 midi files. 
it uses one hour for only 1 epoch.

**Comment by calclavia** [comment]
Training time is slow in general because the Biaxial architecture is large. While training time is independent to the number of midi files, convergence time should be faster given less midi files

**Comment by JucyCherry** [comment]
thank u!! 
And  will the parameter "BATCH_SIZE" affect the effect of the music finally generated?

**Comment by calclavia** [comment]
@JucyCherry Batch size should not affect much.

**Comment by JucyCherry** [comment]
thank u very  much!!
