### ISSUE TITLE
How to write the command line to generate music of different styles?

### ISSUE THREAD

**Issue by JucyCherry** [calclavia/DeepJ#75]
the genres and stylesc I set are like this:

genre = [
    'jazz',
    'classical',
    'hip_hop'
]

styles = [
    [
        'data/jazz/CharlieParker',
        'data/jazz/DavidLiebman',
        'data/jazz/JJJohnson'
    ],
    [
        'data/classical/beethoven',
        'data/classical/holst',
        'data/classical/stravinsky'
        'data/classical/sullivan'
    ],
    [
        'data/hip_hop/50_cent',
        'data/hip_hop/ja_rule',
        'data/hip_hop/pitbull',
        'data/hip_hop/will_smith',
    ]
]

How to write the command line to generate music of different styles.

I use " python generate.py -h" to get the optional arguments,it says:
 --styles STYLES [STYLES ...]  Styles to mix together

but i can't figure out the specific usage of the style control:

i have tried  " python generate.py --styles classical"and " python generate.py --styles classical[beethoven holst],
both showing "error: argument --styles: invalid int value: 'beethoven'"

**Comment by JucyCherry** [comment]
@calclavia I have been reading the paper "DeepJ: Style-Speciﬁc Music Generation",
i can't find the access to the generated music.
Is there  an access to show how the effect of the music you generated.?
And I look through all issuses but can't find the CL problom above ... I have tried much but it still can't work.

**Comment by taylorshin12** [comment]
The style argument takes in an int. If you wanted to generate classical music, the command to do so would be `python generate.py --style 1` assuming you have the styles [jazz, classical, hiphop].

**Comment by JucyCherry** [comment]
@taylorshin12 Thanks a lot!!~
